---
title: Instructor bios
output: html_document
---

#### Abhijit Dasgupta, PhD

Dr. Dasgupta is a biostatistician and data scientist with experience in statistical 
modeling and machine learning, bioinformatics, optimization, signal processing, and 
data visualization. He holds a PhD in Biostatistics with earlier training in Mathematical
Statistics. He has been using R for over 20 years for a wide variety of applications in biomedical 
research, as well as for data-driven reports and presentations. He co-organizes
the [Statistical Programming DC](http://www.meetup.com/stats-prog-dc) meetup (formerly R Users Group DC)
and served on the Board of [Data Community DC](http://www.datacommunitydc.org). He 
regularly gives workshops and webinars on using R and Python for data analysis, machine learning and visualization. He currently serves as co-chair of the Bioinformatics and Data Science department at FAES. 

Dr. Dasgupta serves as a consultant to the [National Institute of Arthritis, Musculoskeletal
and Skin Disorders](https://www.niams.nih.gov/about/directory/abhijit-dasgupta-phd){target=_blank}, part of the NIH, where he works on complex analyses of healthcare databases as
well as outcomes research. He also is
Co-Founder and Chief Data Scientist at [Zansors](http://www.zansors.com){target=_blank}, a healthcare
wearable and analytics company based in Arlington, Virginia. Dr. Dasgupta is a certified [Carpentries](http://www.carpentries.org){target=_blank} instructor, and, with [District Data Labs](http://www.districtdatalabs.com){target=_blank}, he provides high quality cirruculum development and training in data science programming using R and Python. 
